import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import {StrictMode} from "react";
import "../assets/style/main.scss";
import Section1 from "@/homeComponents/Section1";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <StrictMode>
          <main>
            {children}
            <Section1></Section1>
          </main>
        </StrictMode>
        <Footer></Footer>
      </body>
    </html>
  );
}
